### ISSUE TITLE
Feature request: Sort by option

### ISSUE THREAD

**Issue by Raviu8** [famzah/ping-multi#4]
Hi,
Thanks for the fantastic piece of code.
Can you add an option to sort by the selected stats column?
So when you choose least, avg, loss% or so, you can sort ascending or descending.

**Comment by famzah** [comment]
Hi,

That's a good idea. I'll look into it but give me at least a couple of days.

**Comment by Raviu8** [comment]
Thanks,
Would be better if it is a switchable key in the ncurses interface, I think.
Also, would be very nice if you can export a csv file with all stats - / Loss% Avg Min Max StDev RX_cnt TX_cnt XX_cnt / - preceded by two columns of hostname and the resolved IP address.
So one can do whatever analysis using 3rd party tools.

**Comment by Raviu8** [comment]
Any updates?

**Comment by famzah** [comment]
I've implemented the "sort by" feature but named it "Order by", so that the first letter can be used as a shortcut ("s" is already taken by "Stats").

Please take a look. If you have suggestions, feel free to comment and/or re-open this issue.

**Comment by famzah** [comment]
Regarding the stats export -- please open a separate issue. We need to discuss it a bit more. Additionally, a separate issue makes code audit easier.
